### ISSUE TITLE
[BUG]: Dashboard SideBar Responsiveness issue

### ISSUE THREAD

**Issue by sumitd94** [Multiwoven/multiwoven#101]
## Description
In few Screen sizes , the dashboard sidebar content collapsed with each other.

<img width="764" alt="image" src="https://github.com/Multiwoven/multiwoven-ui/assets/22514881/8b4863fa-a701-4415-b408-8e3078d1aab0">

## Steps to Reproduce
1. Login to the Dashboard.
2. Check the UI of Dashboard in different screen sizes to populate the issue.

## Expected Behavior
Collided content should be aligned properly. Dashboard Sidebar should look similar to the below screenshot:

<img width="223" alt="image" src="https://github.com/Multiwoven/multiwoven-ui/assets/22514881/0e2ca918-665b-4258-97ea-75a1b1cfab59">

## Possible Solution
Need to fix the required styles in the sidebar component for alignment issues in all the screen resolution.

**Comment by xyfer17** [comment]
@sumitd94  could you please assign this issue to me.

**Comment by xyfer17** [comment]
@Mohith93 Can you Please take a look on the [PR](https://github.com/Multiwoven/multiwoven/pull/401) for the above issue.
Thanks :)

**Comment by sumitd94** [comment]
#401 Closing this as its solved.
