### ISSUE TITLE
Documentation is not working

### ISSUE THREAD

**Issue by sdepablos** [Multiwoven/multiwoven#124]
**Describe the bug**
The documentation [https://docs.multiwoven.com/](https://docs.multiwoven.com/) is not working, returning a 404

**To Reproduce**

1. Go to [https://docs.multiwoven.com/](https://docs.multiwoven.com/)
2. Get a 404 error

**Expected behavior**
We should see the doucmentation

**Screenshots**

![image](https://uploads.linear.app/67c23673-3981-4107-8206-e84a1601b319/85553b10-c4ed-4c72-8f9b-89266c220083/c0a53bfd-13ad-4382-a25f-ce73beec421b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY3YzIzNjczLTM5ODEtNDEwNy04MjA2LWU4NGExNjAxYjMxOS84NTU1M2IxMC1jNGVkLTRjNzItOGY5Yi04OTI2NmMyMjAwODMvYzBhNTNiZmQtMTNhZC00MzgyLWEyNWYtY2U3M2JlZWM0MjFiIiwiaWF0IjoxNzE1Nzc0OTQ5LCJleHAiOjMzMjg2MzM0OTQ5fQ.mJGIZpn6aap_IH3OaAS1A14c8E5n3ZIIr1CQE4CCWx8)

**Comment by sumitd94** [comment]
This is fixed.
Docs are now pointing to - https://docs.squared.ai/open-source/introduction
