### ISSUE TITLE
CORS error when deploying on Linode (Docker Compose)

### ISSUE THREAD

**Issue by jdbohrman** [Multiwoven/multiwoven#188]
**Describe the bug**

I'm following the steps to try and deploy with Docker Compose but I keep running into a perpetual CORS error on Linode:

```
Access to XMLHttpRequest at 'http://172.105.151.110/:3000/api/v1/signup' from origin 'http://172.105.151.110:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**To Reproduce**
1. Go to 'http://172.105.151.110:8000/sign-up'
2. Try to sign up
3. Inspect the page

**Expected behavior**
You get logged in
**Screenshots**
<img width="568" alt="Screenshot 2024-06-14 at 11 03 52 PM" src="https://github.com/Multiwoven/multiwoven/assets/27848025/8d3fa097-01c0-4d72-82e3-b9695238dcb5">

** Cloud

Linode Debian VM

**Comment by AngeloB-AIS** [comment]
<img width="314" alt="Screenshot 2024-06-17 at 12 41 53 PM" src="https://github.com/Multiwoven/multiwoven/assets/92221369/6f331631-81a8-4e09-b19b-a4433b303c6e">
 Hi @jdbohrman , there is a forward slash between the IP address and the port in your VITE_API_HOST variable. Try removing that wherever you are setting it, most likely in the .env file, and redeploy the docker-compose file.
