### ISSUE TITLE
Unable to Connect to Temporal Cloud 

### ISSUE THREAD

**Issue by TudorAF** [Multiwoven/multiwoven#284]
**Describe the bug**
👋  Hello. not sure if this is just me.  I cloned the repo to try and get it going to play around with it. I have a temporal cloud already stood up and tried to connect but I get the connection issue where the SSL_ERROR is unable to pass the handshake ```outines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED. debug_error_string:{UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses``` . 

I have a python worker using temporal's sdk with these same certs running locally perfectly fine.  I have tried various versions of coinbase gem and cant get it going. 

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.6.1
 
**Additional context**
I copied some of the ruby code for getting a worker started to see what was going on and try and get some gems working together but end up with the same error with the same certs. https://github.com/TudorAF/temporal-test

**Comment by AngeloB-AIS** [comment]
Hi @TudorAF, based on the error message in your repo, it looks like your URL has the port appended twice `testing-sdk.gsllh.tmprl.cloud:7233:7233:`. This is probably the source of your error. At most, it should be appended once.
