### ISSUE TITLE
Change the documentation link

### ISSUE THREAD

**Issue by sangkum** [Multiwoven/multiwoven#408]
**Describe the bug**
Change the documentation link to "https://docs.squared.ai/guides/core-concepts"

**To Reproduce**
1. Login into application
2. Click on Documentation
3. Observe

Actual Result: Currently, its redirecting to "https://docs.multiwoven.com/get-started/introduction".

**Expected behavior** :Change the documentation link to "https://docs.squared.ai/guides/core-concepts"

**Screenshots** 
<img width="1512" alt="Screenshot 2024-10-14 at 10 34 44 PM" src="https://github.com/user-attachments/assets/6d0e6af6-1cd9-45e6-b301-57584a422279">

**Comment by i-sanjay-cs** [comment]
Assign me @sangkum

**Comment by blissbug** [comment]
Hey! @sangkum i would like to work on this issue, can you please assign this to me?

**Comment by SanchitMahajan236** [comment]
Please assign me this issue. I would love to contribute.

**Comment by rahul-chakradhari** [comment]
assign to me

**Comment by xyfer17** [comment]
@sangkum I've updated the documentation link, raise a PR --> https://github.com/Multiwoven/multiwoven/pull/410
please review it.
